# Generated by Django 3.2.9 on 2021-12-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('detailed', models.CharField(max_length=30)),
                ('doctype', models.CharField(choices=[('NIT', 'NIT'), ('AT', 'AT'), ('ID', 'ID')], default='NIT', max_length=5)),
                ('docnum', models.CharField(max_length=30)),
                ('employees', models.IntegerField()),
                ('logo', models.ImageField(upload_to='')),
                ('state', models.CharField(choices=[('PENDING', 'PENDING'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=10)),
            ],
        ),
    ]
