# Generated by Django 3.2.9 on 2021-12-04 01:26

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('genteprevalente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('E:/static')),
        ),
    ]
