# Generated by Django 3.2.9 on 2021-12-04 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genteprevalente', '0003_auto_20211203_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='files',
        ),
    ]
